---
kind: pipeline
type: kubernetes
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: golang:1.14.15
  commands:
  - go test ./...
  
- name: build
  image: golang:1.14.15
  commands:
  - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux

- name: publish
  image: plugins/ecr
  settings:
    repo: lemontech/drone
    registry: 786298960439.dkr.ecr.us-east-1.amazonaws.com
    dockerfile: docker/Dockerfile.server.linux.amd64
    auto_tag: true
    auto_tag_suffix: linux-amd64
  when:
    event:
    - push
    - tag
